name: 'Daily Tests'

on:
  pull_request:
  schedule:
    - cron:  '0 11 * * *'

jobs:
    test-php:
        env:
            WC_CORE_DIR: /home/runner/work/_temp/wordpress/wp-content/plugins/woocommerce
            COMPOSER_DEV: 1

        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4']
                wordpress: ['latest', 'nightly']
                woocommerce: ['latest', 'nightly']
                phpunit: ['7.5.20']
                composer: ['2.0.6']
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.7.0
              with:
                  access_token: ${{ github.token }}
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@2.9.0
              with:
                  php-version: ${{matrix.php}}
                  tools: phpunit:${{matrix.phpunit}}
                  extensions: mysqli
            - name: Setup Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'
            - name: Set up the tests
              env:
                  WP_VERSION: ${{matrix.wordpress}}
                  WC_VERSION: ${{matrix.woocommerce}}
                  PHP_UNIT: ${{matrix.phpunit}}
                  COMPOSER_VERSION: ${{matrix.composer}}
              run: |
                  sudo /etc/init.d/mysql start
                  bash bin/install-wp-tests.sh wc_admin_test root 'root' localhost
            - name: Run the PHP unit tests
              run: phpunit -c phpunit.xml.dist
              shell: bash
