name: 'Daily Tests'

on:
  pull_request:
  schedule:
    - cron:  '0 11 * * *'

jobs:
    test-php:
        env:
            COMPOSER_DEV: 1

        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4']
                wordpress: ['latest', 'nightly']
                woocommerce: ['latest', 'nightly']
                phpunit: ['7.5.20']
                composer: ['2.0.6']
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.7.0
              with:
                  access_token: ${{ github.token }}
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'
            - name: Run Composer Install
              run: composer install
              shell: bash
            - name: Run the PHP unit tests
              run: npm run test:php
              shell: bash
